# Runs 5 unit tests in Google Cloud Build.
steps:
  - name: 'node:20'
    id: install
    entrypoint: npm
    args: ['ci']

  - name: 'node:20'
    id: unit-tests
    waitFor: ['install']
    entrypoint: npm
    args: ['run', 'test:unit:cloud']

options:
  logging: CLOUD_LOGGING_ONLY
