#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────
# setup-log-alerts.sh
#
# Creates Cloud Logging log-based alerts in GCP so the team is
# notified by email when critical events occur — no manual
# log-checking required for severe issues.
#
# Run once after deploying to Cloud Run:
#   bash scripts/setup-log-alerts.sh
#
# Prerequisites:
#   gcloud auth login
#   gcloud config set project dotted-spot-476513-i2
# ─────────────────────────────────────────────────────────────

set -euo pipefail

PROJECT_ID="dotted-spot-476513-i2"
SERVICE="christhood-cmms"
REGION="us-central1"
NOTIFICATION_EMAIL="${ALERT_EMAIL:-admin@christhood.org}"  # override with: ALERT_EMAIL=you@example.com bash setup-log-alerts.sh

echo "==> Project:  $PROJECT_ID"
echo "==> Service:  $SERVICE"
echo "==> Alerting: $NOTIFICATION_EMAIL"
echo ""

# ── Step 1: Create an email notification channel ──────────────────────────────
echo "==> Creating email notification channel..."
CHANNEL_JSON=$(gcloud alpha monitoring channels create \
  --display-name="Christhood CMMS Alerts" \
  --type=email \
  --channel-labels="email_address=${NOTIFICATION_EMAIL}" \
  --project="$PROJECT_ID" \
  --format=json 2>/dev/null || true)

# Fetch the channel name (may already exist)
CHANNEL_NAME=$(gcloud alpha monitoring channels list \
  --project="$PROJECT_ID" \
  --filter="displayName='Christhood CMMS Alerts'" \
  --format="value(name)" \
  --limit=1)

if [[ -z "$CHANNEL_NAME" ]]; then
  echo "ERROR: Could not create or find notification channel. Check gcloud auth." >&2
  exit 1
fi
echo "    Channel: $CHANNEL_NAME"
echo ""

# ── Helper: create a log-based alert policy ───────────────────────────────────
create_alert() {
  local name="$1"
  local display_name="$2"
  local filter="$3"
  local duration="${4:-0s}"   # 0s = alert on first occurrence

  echo "==> Creating alert: $display_name"

  gcloud alpha monitoring policies create \
    --display-name="[CMMS] $display_name" \
    --condition-display-name="$display_name" \
    --condition-filter="$filter" \
    --condition-duration="$duration" \
    --notification-channels="$CHANNEL_NAME" \
    --documentation="Auto-generated by setup-log-alerts.sh for $SERVICE on $PROJECT_ID" \
    --project="$PROJECT_ID" \
    --quiet 2>/dev/null \
    && echo "    Created." \
    || echo "    Already exists or skipped."
  echo ""
}

BASE_FILTER='resource.type="cloud_run_revision" resource.labels.service_name="'"$SERVICE"'"'

# ── Alert 1: Any ERROR severity log ───────────────────────────────────────────
create_alert "cmms-any-error" \
  "Any 500 / API Error" \
  "$BASE_FILTER severity=ERROR"

# ── Alert 2: Upload failures ──────────────────────────────────────────────────
create_alert "cmms-upload-failed" \
  "File Upload Failed" \
  "$BASE_FILTER jsonPayload.event=\"FILE_UPLOAD_FAILED\""

# ── Alert 3: Login failures (brute-force detection) ──────────────────────────
# Alert only after 5 login failures in 5 minutes (threshold via window)
create_alert "cmms-login-failed" \
  "Login Failures (5+ in 5 min)" \
  "$BASE_FILTER jsonPayload.event=\"USER_LOGIN_FAILED\"" \
  "300s"

# ── Alert 4: Slow operations > 3 s ───────────────────────────────────────────
create_alert "cmms-slow-operation" \
  "Slow Operation Detected" \
  "$BASE_FILTER jsonPayload.event=\"SLOW_OPERATION\""

# ── Alert 5: Zara AI errors ───────────────────────────────────────────────────
create_alert "cmms-zara-error" \
  "Zara AI Error" \
  "$BASE_FILTER jsonPayload.event=\"ZARA_ERROR\" severity>=WARNING"

# ── Alert 6: Transfer complete / cancelled ────────────────────────────────────
# Not an error alert — informational only; keep commented unless desired.
# create_alert "cmms-transfer-cancelled" \
#   "Transfer Cancelled" \
#   "$BASE_FILTER jsonPayload.event=\"TRANSFER_CANCELLED\""

# ── Alert 7: Cron purge failures ──────────────────────────────────────────────
create_alert "cmms-purge-failed" \
  "File Purge Cron Failure" \
  "$BASE_FILTER jsonPayload.event=\"FILE_PURGE_FAILED\""

echo "✓ All alert policies configured."
echo ""
echo "Next steps:"
echo "  1. Go to https://console.cloud.google.com/monitoring/alerting?project=$PROJECT_ID"
echo "  2. Confirm each policy shows 'Enabled'"
echo "  3. Check your email ($NOTIFICATION_EMAIL) for a verification email from Google"
echo "  4. Open Logs Explorer: https://cloudlogging.app.goo.gl/1Zs"
echo ""
echo "Logs Explorer — paste these as saved queries:"
echo ""
echo "  All Errors Today:"
echo '    resource.type="cloud_run_revision" severity=ERROR timestamp>="today"'
echo ""
echo "  Zara Issues:"
echo '    resource.type="cloud_run_revision" jsonPayload.event=~"ZARA" severity>=WARNING'
echo ""
echo "  Upload Failures:"
echo '    resource.type="cloud_run_revision" jsonPayload.event="FILE_UPLOAD_FAILED"'
echo ""
echo "  Login Failures:"
echo '    resource.type="cloud_run_revision" jsonPayload.event="USER_LOGIN_FAILED"'
echo ""
echo "  Slow Operations:"
echo '    resource.type="cloud_run_revision" jsonPayload.event="SLOW_OPERATION"'
echo ""
echo "  All 500 Errors:"
echo '    resource.type="cloud_run_revision" jsonPayload.event="API_ERROR" severity=ERROR'
