import { NextRequest, NextResponse } from 'next/server'
import { handleApiError } from '@/lib/apiError'
import { getServerSession } from 'next-auth'
import { authOptions }      from '@/lib/auth'
import { getPresignedPartUrl } from '@/lib/r2'

/**
 * POST /api/upload/multipart/refresh-urls
 *
 * Re-generates presigned PUT URLs for parts of an existing R2 multipart session.
 *
 * Use this when a chunk upload fails with HTTP 403 (presigned URL expired).
 * Presigned URLs generated by /multipart/presign are valid for 1 hour. If an
 * upload is interrupted for longer than that, this endpoint returns fresh URLs
 * for the specific parts that still need to be uploaded.
 *
 * The R2 multipart session itself remains valid for 7 days from creation.
 *
 * Body:    { uploadId: string, key: string, partNumbers: number[] }
 * Returns: { presignedUrls: { partNumber: number, url: string }[] }
 */
export async function POST(req: NextRequest) {
  const session = await getServerSession(authOptions)
  if (!session?.user?.id) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const body = await req.json().catch(() => ({})) as {
    uploadId?:    string
    key?:         string
    partNumbers?: number[]
  }

  const { uploadId, key, partNumbers } = body

  if (!uploadId || !key || !Array.isArray(partNumbers) || partNumbers.length === 0) {
    return NextResponse.json(
      { error: 'Missing required fields: uploadId, key, partNumbers (non-empty array)' },
      { status: 400 },
    )
  }

  if (partNumbers.length > 10_000) {
    return NextResponse.json({ error: 'partNumbers may not exceed 10,000 entries' }, { status: 400 })
  }

  if (partNumbers.some(n => !Number.isInteger(n) || n < 1 || n > 10_000)) {
    return NextResponse.json(
      { error: 'Each partNumber must be an integer between 1 and 10,000' },
      { status: 400 },
    )
  }

  try {
    const presignedUrls = await Promise.all(
      partNumbers.map(async partNumber => ({
        partNumber,
        url: await getPresignedPartUrl(key, uploadId, partNumber, 3600),
      })),
    )

    return NextResponse.json({ presignedUrls })
  } catch (err: unknown) {
    return handleApiError(err, 'multipart/refresh-urls')
  }
}
